#!/bin/csh

#
# Install
#
# Installs product "snpcacheload" in the appropriate directory
#
# 1. cvs export -r snpcacheload-#-#-# -d snpcacheload-#-#-# snpcacheload
# 2. ln -s snpcacheload-#-#-# snpcacheload
# 3. Copy Configuration.default Configuration
# 4. Edit Configuration
#

cd `dirname $0` && source ./Configuration

if ( ! -d ${CACHEDIR} ) then
        mkdir -p ${CACHEDIR}
endif

if ( ! -d ${CACHEDATADIR} ) then
        mkdir -p ${CACHEDATADIR}
endif

if ( ! -d ${CACHELOGSDIR} ) then
        mkdir -p ${CACHELOGSDIR}
endif

