#!/bin/sh

#
# Install
#
# Installs product "snpcacheload" in the appropriate directory
#
# 1. cvs export -r snpcacheload-#-#-# -d snpcacheload-#-#-# snpcacheload
# 2. ln -s snpcacheload-#-#-# snpcacheload
# 3. Copy Configuration.default Configuration
# 4. Edit Configuration
# 5. Install

cd `dirname $0` && . ./Configuration

if [ ! -d ${CACHEDIR} ]
then
        mkdir -p ${CACHEDIR}
fi

if [ ! -d ${CACHEDATADIR} ] 
then
        mkdir -p ${CACHEDATADIR}
fi

if [ ! -d ${CACHELOGSDIR} ] 
then
        mkdir -p ${CACHELOGSDIR}
fi

if [ ! -d ${ARCHIVEDIR} ] 
then
        mkdir -p ${ARCHIVEDIR}
fi
